'use client';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {BookOpen,MessageSquare,LayoutDashboard,Sprout,ShieldCheck,Wifi,WifiOff,Plus,Download,Check,ChevronRight,Globe,HardDrive,Loader2,FlaskConical,Trash2,Upload,Quote,Lightbulb,Clock,Star,Search,X,NotebookPen,Leaf,CheckCircle2,Info,LockKeyhole} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {COPY} from '@/lib/i18n';
import {DEFAULT_STATE,THEMES,summarize,uniqueReviews,scrub,validateImport,mergeAnalysis,type State,type Review,type ThemeId,type Experiment,type Tone} from '@/lib/domain';
import {analyzeCompact,analyzeSemantic,loadSemantic,MODEL_BYTES} from '@/lib/engine';
const STORAGE='noor-fieldnotes-v1';
const uuid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const icons=[LayoutDashboard,MessageSquare,Sprout,HardDrive];
const views=['overview','feedback','actions','device'] as const;
type View=typeof views[number];
type InstallPrompt=Event&{prompt:()=>Promise<unknown>};
type Evaluation={total:number;semanticAccuracy:number;baselineAccuracy:number;compactAccuracy:number};
type ModelContext={registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown};
function download(name:string,data:string){const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function displayDate(date:string){return new Date(`${date.slice(0,10)}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'});}
export default function Fieldnotes({initialView='overview',initialLanguage}:{initialView?:View;initialLanguage?:'en'|'sw'}={}){
 const [state,setState]=useState<State>(DEFAULT_STATE),[loaded,setLoaded]=useState(false),[view,setView]=useState<View>(initialView),[online,setOnline]=useState(true),[desktop,setDesktop]=useState(false),[addOpen,setAddOpen]=useState(false),[detail,setDetail]=useState<ThemeId|null>(null),[busy,setBusy]=useState(false),[semantic,setSemantic]=useState(false),[progress,setProgress]=useState(''),[offlineReady,setOfflineReady]=useState(false),[offlineProfile,setOfflineProfile]=useState<'core'|'full'>('core'),[installPrompt,setInstallPrompt]=useState<InstallPrompt|null>(null),[deleteOpen,setDeleteOpen]=useState(false),[ownOpen,setOwnOpen]=useState(false),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[showEvaluation,setShowEvaluation]=useState(false),[evaluation,setEvaluation]=useState<Evaluation|null>(null),[resultOpen,setResultOpen]=useState<Experiment|null>(null),[resultText,setResultText]=useState(''),[newText,setNewText]=useState(''),[newDate,setNewDate]=useState(today()),[newRating,setNewRating]=useState('none'),[newSource,setNewSource]=useState('Guest conversation'),[newLanguage,setNewLanguage]=useState('en'),[consent,setConsent]=useState(false),[batch,setBatch]=useState(false),[planNote,setPlanNote]=useState(''),[storageError,setStorageError]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),c=COPY[state.language],sw=state.language==='sw';
 const set=(patch:Partial<State>)=>setState(s=>({...s,...patch}));
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Hydrate device storage after mount.
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw)setState({...validateImport(JSON.parse(raw)),...(initialLanguage?{language:initialLanguage}:{})});else if(initialLanguage)setState(s=>({...s,language:initialLanguage}));}catch{setStorageError(true);}setLoaded(true);setOnline(navigator.onLine);const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);const install=(e:Event)=>{e.preventDefault();setInstallPrompt(e as InstallPrompt);};window.addEventListener('beforeinstallprompt',install);if((window as Window&{noorDesktop?:{offlineIncluded?:boolean}}).noorDesktop?.offlineIncluded){setDesktop(true);setOfflineReady(true);setOfflineProfile('full');loadSemantic().then(()=>setSemantic(true)).catch(()=>setProgress('The semantic model could not load. Compact analysis remains available.'));}else if('serviceWorker'in navigator&&'caches'in window){navigator.serviceWorker.register('/sw.js').catch(()=>{});caches.open('noor-offline-v1').then(async metadata=>{const ready=await metadata.match('/offline-ready.json');if(ready){const saved=await ready.json() as {cacheName:string;profile:string};const cache=await caches.open(saved.cacheName);setOfflineReady(!!await cache.match('/offline/index.html'));setOfflineProfile(saved.profile==='full'?'full':'core');if(saved.profile==='full')loadSemantic().then(()=>setSemantic(true)).catch(()=>{});}}).catch(()=>{});}fetch('/evaluation.json').then(r=>r.ok?r.json():null).then(v=>setEvaluation(v as Evaluation|null)).catch(()=>{});return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);window.removeEventListener('beforeinstallprompt',install);};},[initialLanguage]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Report storage failures to the operator.
 useEffect(()=>{if(loaded){try{localStorage.setItem(STORAGE,JSON.stringify(state));window.dispatchEvent(new Event('noor-feedback-updated'));}catch{setStorageError(true);}}document.documentElement.lang=state.language;},[state,loaded]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Analyze hydrated records once; preserve human corrections.
 useEffect(()=>{if(loaded)setState(s=>({...s,reviews:mergeAnalysis(s.reviews,s.reviews.map(r=>({...r,analysis:analyzeCompact(r)})))}));},[loaded]);
 const reviewSnapshot=useRef(state.reviews);
 useEffect(()=>{reviewSnapshot.current=state.reviews;},[state.reviews]);
 useEffect(()=>{let cancelled=false;if(loaded&&semantic){(async()=>{setBusy(true);try{const updated:Review[]=[];for(const r of reviewSnapshot.current)updated.push({...r,analysis:await analyzeSemantic(r)});if(!cancelled)setState(s=>({...s,reviews:mergeAnalysis(s.reviews,updated)}));}catch{if(!cancelled){setSemantic(false);setProgress('Richer analysis is unavailable. Compact analysis and human review remain available.');}}finally{if(!cancelled)setBusy(false);}})();}return()=>{cancelled=true;};},[loaded,semantic]);
 const distinct=useMemo(()=>uniqueReviews(state.reviews),[state.reviews]);const insights=useMemo(()=>summarize(state.reviews),[state.reviews]);const top=insights.find(t=>t.issues>=2)??insights.find(t=>t.mentions>=2);const uncertain=distinct.filter(r=>r.analysis?.some(a=>!a.theme)).length;const selected=insights.find(t=>t.id===detail);
 const shown=distinct.filter(r=>r.text.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(filter==='uncertain'?r.analysis?.some(a=>!a.theme):r.analysis?.some(a=>a.theme===filter))));
 async function analyze(useSemantic=semantic){setBusy(true);try{const all:Review[]=[];for(const r of state.reviews){all.push({...r,analysis:useSemantic?await analyzeSemantic(r):analyzeCompact(r)});}setState(s=>({...s,reviews:mergeAnalysis(s.reviews,all)}));toast.success(sw?'Maoni yamechambuliwa.':'Feedback analyzed on this device.');}catch{toast.error('Analysis could not complete. Your comments are safe.');}finally{setBusy(false);}}
 async function prepare(profile:'core'|'full'='core'){if(desktop){await activateSemantic();return;}setBusy(true);setProgress('Preparing the offline package…');try{if(!('serviceWorker' in navigator))throw new Error('Offline installation needs HTTPS or localhost. Use the deployed app or the supplied localhost package.');const registration=await navigator.serviceWorker.ready;const channel=new MessageChannel();let timeout:ReturnType<typeof setTimeout>;const cachePromise=new Promise<void>((resolve,reject)=>{timeout=setTimeout(()=>reject(new Error('Offline setup timed out. Try again while connected.')),180000);channel.port1.onmessage=e=>{if(e.data.status==='progress')setProgress(`Saving offline files: ${e.data.done}/${e.data.total}`);if(e.data.status==='ready'){clearTimeout(timeout);resolve();}if(e.data.status==='error'){clearTimeout(timeout);reject(new Error(e.data.error));}};});if(!registration.active){channel.port1.close();throw new Error('Offline installation is still starting. Try again.');}registration.active.postMessage({type:'PREPARE_OFFLINE',profile},[channel.port2]);await cachePromise;channel.port1.close();setOfflineReady(true);setOfflineProfile(profile);if(profile==='full'){setProgress('Loading the semantic model…');await loadSemantic(setProgress);setSemantic(true);set({modelReady:true});}setProgress(profile==='full'?'Ready. Richer AI is saved for offline use.':'Ready. Compact AI and the notebook are saved for offline use.');toast.success('Offline package is ready. Reopen it in airplane mode to check.');}catch(e){setProgress(e instanceof Error?e.message:'Offline setup failed.');toast.error('Setup did not finish. Your feedback is unchanged.');}finally{setBusy(false);}}
 async function activateSemantic(){setBusy(true);setProgress('Loading richer analysis on this device…');try{await loadSemantic(setProgress);if(semantic)await analyze(true);else setSemantic(true);set({modelReady:true});setProgress(desktop?'Semantic analysis is ready. All assets are included on this computer.':'Semantic analysis is ready. Save the full package for offline use.');toast.success('Richer analysis loaded on this device.');}catch(e){setProgress(e instanceof Error?e.message:'Model unavailable.');toast.error('The semantic model could not load. Compact analysis remains available.');}finally{setBusy(false);}}
 async function addFeedback(){const pieces=batch?newText.split(/\n\s*\n/):[newText];const values=pieces.map(scrub).filter(t=>t.length>2);if(!consent||!values.length){toast.error('Add a comment and confirm permission.');return;}if(state.reviews.length+values.length>1000){toast.error('This device supports up to 1,000 comments.');return;}const rs:Review[]=values.slice(0,100).map((text)=>({id:`review-${uuid()}`,text,date:newDate,rating:newRating==='none'?null:Number(newRating),source:scrub(newSource).slice(0,100),synthetic:state.mode==='demo',consent:true,language:newLanguage as Review['language']}));setBusy(true);try{for(const r of rs)r.analysis=semantic?await analyzeSemantic(r):analyzeCompact(r);setState(s=>({...s,reviews:[...rs,...s.reviews]}));setNewText('');setConsent(false);setAddOpen(false);toast.success(`${rs.length} ${sw?'maoni yamehifadhiwa':'comment(s) saved on this device'}`);}catch{toast.error('Feedback could not be analyzed. Your draft remains in the form.');}finally{setBusy(false);}}
 function plan(theme:ThemeId){const item=insights.find(t=>t.id===theme)!;if(state.experiments.some(e=>e.theme===theme&&e.status!=='complete')){toast.info('You already have an improvement planned for this theme.');return;}const exp:Experiment={id:uuid(),theme,title:sw?item.actionSw:item.actionEn,status:'planned',createdAt:new Date().toISOString(),baselineCount:item.mentions,baselineIssues:item.issues,note:scrub(planNote)};setState(s=>({...s,experiments:[exp,...s.experiments]}));setPlanNote('');setDetail(null);setView('actions');toast.success(sw?'Mpango umehifadhiwa.':'Your decision is saved. Nothing is sent to guests.');}
 function correct(reviewId:string,index:number,theme:string,tone:Tone){setState(s=>({...s,reviews:s.reviews.map(r=>r.id===reviewId?{...r,analysis:r.analysis?.map((a,i)=>i===index?{...a,theme:theme==='unknown'?null:theme as ThemeId,tone,corrected:true}:a)}:r)}));}
 async function restore(file:File){try{if(file.size>10_000_000)throw new Error('Backup is too large.');const next=validateImport(JSON.parse(await file.text()));next.reviews=mergeAnalysis(next.reviews,next.reviews.map(r=>({...r,analysis:analyzeCompact(r)})));setState(next);toast.success('Backup restored on this device.');}catch(e){toast.error(e instanceof Error?e.message:'Cannot restore this backup.');}}
 useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools=[{name:'read_guest_insights',description:'Read current guest themes and their evidence. Does not modify feedback.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({comments:distinct.length,themes:insights.map(t=>({theme:t.id,mentions:t.mentions,issues:t.issues,quotes:t.evidence.slice(0,3).map(e=>e.quote)}))})},{name:'stage_feedback_entry',description:'Open the feedback form for the operator. Does not save feedback or grant consent.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:5000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const i=input as {text:string};if(!i||typeof i.text!=='string'||i.text.length>5000)throw new Error('Invalid text.');setNewText(scrub(i.text));setConsent(false);setAddOpen(true);return {status:'staged',requiresHumanConsent:true};}}];for(const t of tools){try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{/* Optional browser API; the visible workflow remains available. */}}return()=>life.abort();},[distinct,insights]);
 const nav=views.map((v,i)=>({view:v,label:c[v],Icon:icons[i]}));
 return <SidebarProvider className="noor-shell" style={{'--sidebar-width':'238px'} as CSSProperties}>
 <Sidebar collapsible="none" className="noor-sidebar"><SidebarHeader className="brand"><span className="brand-mark">n</span><div>FarmPilot<span>FEEDBACK</span></div></SidebarHeader><SidebarContent><div className="farm-label"><span className="farm-avatar"><Leaf size={19}/></span><div><strong>{state.business}</strong><span>{sw?'Daftari la wageni':'Your guest notebook'}</span></div></div><div className="nav-caption">{sw?'NAFASI YAKO':'YOUR WORKSPACE'}</div><SidebarMenu className="nav-menu">{nav.map(({view:v,label,Icon})=><SidebarMenuItem key={v}><SidebarMenuButton isActive={view===v} onClick={()=>setView(v)} className="nav-button"><Icon size={19}/><span>{label}</span>{v==='feedback'&&<b>{distinct.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><NotebookPen size={24}/><p>{sw?'Kila maoni yanaweza kuanzisha kitu kizuri.':'Every guest’s words can be the start of something good.'}</p></div></SidebarContent><SidebarFooter className="side-bottom"><div className="device-badge"><ShieldCheck size={17}/><span>{sw?'AI kwenye kifaa chako':'AI on your device'}</span></div><button onClick={()=>setView('device')}><span className="avatar">N</span><span>Noor<small>{sw?'Mmiliki wa shamba':'Farm owner'}</small></span><ChevronRight size={17}/></button></SidebarFooter></Sidebar>
 <div className="main-area"><header className="topbar"><div className="breadcrumb">Fieldnotes <span>/</span> <strong>{c[view]}</strong></div><div className="top-controls"><span className={`network ${!online?'offline':''}`}>{online?<Wifi size={15}/>:<WifiOff size={15}/>}<span>{desktop?(sw?'Programu ya ndani':'Local app'):online?c.online:c.offline}</span></span><button className="language-button" onClick={()=>set({language:sw?'en':'sw'})} aria-label={sw?'Switch to English':'Badilisha lugha kuwa Kiswahili'}><Globe size={16}/>{sw?'Kiswahili':'English'}</button><span className="avatar small">N</span></div></header>
 <nav className="mobile-nav" aria-label="Main navigation">{nav.map(({view:v,label,Icon})=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}><Icon size={19}/><span>{label}</span></button>)}</nav>
 <main className="workspace">
 {storageError&&<div className="notice error">Storage is unavailable or full. Export a backup before closing this page.</div>}
 {state.mode==='demo'&&<div className="demo-notice"><FlaskConical size={16}/><span>{c.demo}</span><button onClick={()=>setOwnOpen(true)}>{c.own}<ChevronRight size={14}/></button></div>}
 <div className="page-heading"><div><div className="eyebrow">{view==='overview'?(sw?'DAFTARI LA WIKI':'YOUR WEEKLY FIELDNOTES'):c[view].toUpperCase()}</div><h1>{view==='overview'?c.title:c[view]}</h1><p>{view==='overview'?c.subtitle:view==='feedback'?c.local:view==='actions'?c.actionHelp:sw?'Andaa matumizi bila mtandao na linda maoni yako.':'Keep your notebook available, even without a connection.'}</p></div><div className="heading-actions">{view!=='device'&&<button className="primary" onClick={()=>setAddOpen(true)}><Plus size={18}/>{c.add}</button>}</div></div>
 {view==='overview'&&<>
 <div className="stats-row">{([[c.guests,distinct.length,MessageSquare],[c.themes,insights.filter(t=>t.mentions).length,BookOpen],[c.needs,uncertain,Info],[c.improvements,state.experiments.length,Sprout]] as const).map(([label,value,Icon],i)=><div className="stat" key={label}><span className={`stat-icon color-${i}`}><Icon size={19}/></span><div><span>{label}</span><strong>{value}</strong></div>{i===0&&<span className="stat-tag">{state.mode==='demo'?'DEMO':'LOCAL'}</span>}</div>)}</div>
 <div className="overview-grid"><section className="recommendation"><div className="card-top"><span className="label"><Lightbulb size={16}/>{c.recommended}</span><span className="pill light">{sw?'Wewe unaamua':'Your decision'}</span></div>{top?<><div className="recommend-icon"><Sprout size={30}/></div><h2>{sw?top.actionSw:top.actionEn}</h2><p>{sw?`Maoni ${top.mentions} yanahusu mada hii. ${top.issues} yanaomba mabadiliko.`:`${top.mentions} distinct comments mention ${top.en.toLowerCase()}. ${top.issues} comments suggest something could be better.`}</p><div className="recommend-quotes">{top.evidence.filter(e=>e.tone==='improve').slice(0,2).map((e,i)=><div key={i}><Quote size={16}/><p>“{e.quote}”</p></div>)}</div><div className="recommend-bottom"><span><Clock size={15}/>{top.effort}</span><button className="lime" onClick={()=>{setDetail(top.id);setPlanNote('');}}>{c.review}<ChevronRight size={16}/></button></div></>:<div className="empty-inline"><h2>{c.empty}</h2><p>{c.emptyHint}</p><button className="lime" onClick={()=>setAddOpen(true)}>{c.add}</button></div>}</section>
 <section className="panel theme-panel"><div className="panel-heading"><div><h2>{sw?'Wageni wanataja nini?':'What guests are talking about'}</h2><p>{c.statHint}</p></div><span className="icon-outline"><BookOpen size={18}/></span></div><div className="theme-bars">{insights.map(t=><button className="theme-row" key={t.id} onClick={()=>setDetail(t.id)}><div><span className="theme-dot" style={{background:t.color}}/><span>{sw?t.sw:t.en}</span><strong>{t.mentions}</strong></div><div className="bar-track"><div style={{width:`${distinct.length?t.mentions/distinct.length*100:0}%`,background:t.color}}/></div></button>)}</div><div className="legend"><span><i className="legend-dot"/>{sw?'Idadi ya maoni tofauti':'Number of distinct comments'}</span><button onClick={()=>analyze()} disabled={busy}>{busy?<Loader2 className="spin" size={14}/>:<FlaskConical size={14}/>} {busy?c.analyzing:c.analyze}</button></div></section></div>
 <div className="section-heading"><div><h2>{sw?'Sikiliza kwa karibu':'A closer listen'}</h2><p>{sw?'Maneno ya wageni, pamoja na muktadha.':'Guest words, with the context that matters.'}</p></div><button className="text-button" onClick={()=>setView('feedback')}>{sw?'Maoni yote':'View all feedback'}<ChevronRight size={15}/></button></div><div className="feedback-preview">{distinct.slice(0,3).map(r=><ReviewCard key={r.id} review={r} c={c} sw={sw} onOpen={()=>{setView('feedback');setSearch(r.text.slice(0,30));}}/>)}</div>
 <div className="bottom-note"><ShieldCheck size={16}/><span>{c.local} {sw?'Hakuna kinachotumwa kiotomatiki.':'Nothing is sent automatically.'}</span><span>{semantic?'Semantic AI':'Compact AI'} · {(MODEL_BYTES/1024).toFixed(0)} KB compact model</span></div>
 </>}
 {view==='feedback'&&<><div className="feedback-toolbar"><div className="search-box"><Search size={17}/><input aria-label="Search comments" placeholder={sw?'Tafuta maoni…':'Search guest words…'} value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={15}/></button>}</div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{c.all}</SelectItem><SelectItem value="uncertain">{c.ask}</SelectItem>{THEMES.map(t=><SelectItem value={t.id} key={t.id}>{sw?t.sw:t.en}</SelectItem>)}</SelectContent></Select><button className="secondary" disabled={busy} onClick={()=>analyze()}>{busy?<Loader2 className="spin" size={17}/>:<FlaskConical size={17}/>} {c.analyze}</button></div><p className="count-line">{shown.length} {sw?'maoni':'comments'} · {state.reviews.length-distinct.length} {sw?'nakala au yaliyofichwa':'duplicates or excluded comments'}</p><div className="review-list">{shown.map(r=><article className="panel full-review" key={r.id}><div className="review-meta"><span className="guest-avatar"><MessageSquare size={17}/></span><span>{r.synthetic?c.synthetic:r.source}<small>{displayDate(r.date)} · {r.language==='en'?'English':r.language==='sw'?'Kiswahili':'Other language'}</small></span><span className="stars">{r.rating?Array.from({length:r.rating},(_,i)=><Star key={i} size={13} fill="currentColor"/>):null}</span><button className="icon-button" aria-label="Delete comment" onClick={()=>setState(s=>({...s,reviews:s.reviews.filter(x=>x.id!==r.id)}))}><Trash2 size={16}/></button></div><p className="original">{r.text}</p>{r.analysis?.map((a,i)=><div className="analysis-row" key={i}><span className={`tone-pill ${a.theme?a.tone:'uncertain'}`}>{a.theme?(sw?THEMES.find(t=>t.id===a.theme)!.sw:THEMES.find(t=>t.id===a.theme)!.en):c.ask}</span><span className="analysis-tone">{c[a.tone]}{a.corrected?' · Human corrected':''}</span><Select value={a.theme??'unknown'} onValueChange={v=>correct(r.id,i,v,a.tone)}><SelectTrigger className="correction-select" aria-label={c.correction}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unknown">{c.unknown}</SelectItem>{THEMES.map(t=><SelectItem key={t.id} value={t.id}>{sw?t.sw:t.en}</SelectItem>)}</SelectContent></Select><Select value={a.tone} onValueChange={v=>correct(r.id,i,a.theme??'unknown',v as Tone)}><SelectTrigger className="tone-select" aria-label="Correct feedback tone"><SelectValue/></SelectTrigger><SelectContent>{(['positive','improve','uncertain'] as const).map(t=><SelectItem key={t} value={t}>{c[t]}</SelectItem>)}</SelectContent></Select></div>)}</article>)}{!shown.length&&<Empty title={c.empty} text={c.emptyHint} onAdd={()=>setAddOpen(true)} label={c.add}/>}</div></>}
 {view==='actions'&&<>{!state.experiments.length?<Empty title={c.noActions} text={c.await} onAdd={()=>{setView('overview');}} label={c.overview}/>:<div className="experiment-list">{state.experiments.map(e=>{const t=THEMES.find(t=>t.id===e.theme)!;const current=insights.find(t=>t.id===e.theme)!;return <section className="panel experiment" key={e.id}><div className="experiment-heading"><span className="experiment-icon"><Sprout size={24}/></span><div><span className={`status-pill ${e.status}`}>{e.status==='complete'?c.completed:e.status==='active'?c.active:c.planned}</span><h2>{sw?t.actionSw:t.actionEn}</h2></div></div><div className="experiment-evidence"><div><span>{sw?'Maoni kabla ya mpango':'Comments when planned'}</span><strong>{e.baselineCount}</strong></div><div><span>{sw?'Maombi ya mabadiliko kabla':'Requests for change then'}</span><strong>{e.baselineIssues}</strong></div><div><span>{sw?'Maoni ya mada hii sasa':'Theme comments now'}</span><strong>{current.mentions}</strong></div></div><p>{e.note||c.actionHelp}</p>{e.result&&<div className="outcome-note"><CheckCircle2 size={19}/><div><strong>{sw?'Matokeo uliyorekodi':'Your recorded outcome'}</strong><p>{e.result}</p></div></div>}<div className="experiment-footer"><span>{displayDate(e.createdAt)} · {sw?'Uamuzi wako':'Approved by you'}</span>{e.status==='planned'&&<button className="primary" onClick={()=>setState(s=>({...s,experiments:s.experiments.map(x=>x.id===e.id?{...x,status:'active',startedAt:new Date().toISOString()}:x)}))}>{c.start}</button>}{e.status==='active'&&<button className="primary" onClick={()=>{setResultText('');setResultOpen(e);}}>{c.complete}</button>}<button className="text-button" onClick={()=>setDetail(e.theme)}>{c.evidence}</button></div></section>;})}</div>}<p className="honest-note">{sw?'Mabadiliko ya maoni hayaonyeshi kwamba uboreshaji ndio sababu pekee. Rekodi ulichoona.':'Changes in feedback do not establish that an improvement caused the change. Record what you actually observed.'}</p></>}
 {view==='device'&&<div className="device-grid"><section className="panel offline-panel"><span className="large-device-icon"><WifiOff size={30}/></span><h2>{desktop?(sw?'Yote yamehifadhiwa kwenye kompyuta hii':'Everything is included on this computer'):offlineReady?c.ready:c.download}</h2><p>{desktop?(sw?'Programu na AI zote zipo hapa. Maoni na mipango vinafanya kazi bila mtandao.':'The app and both AI models are bundled. Analyze comments and make decisions without an internet connection.'):sw?'Hifadhi programu na AI kwenye simu wakati mtandao upo. Baada ya hapo, uchambuzi na mipango vinafanya kazi bila mtandao.':'Save the app and AI while you have a connection. After setup, analyze new comments and make decisions without internet.'}</p><div className="package-details"><span>Core offline notebook<strong>~2.4 MB · compact AI</strong></span><span>Compact model<strong>{(MODEL_BYTES/1024).toFixed(1)} KB · included</strong></span><span>Semantic model<strong>48 MB full offline package</strong></span><span>Guest feedback<strong>{sw?'Kifaa hiki pekee':'This device only'}</strong></span></div>{!desktop&&<><button className="primary wide" onClick={()=>prepare('core')} disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<Download size={18}/>} {busy?'Preparing…':offlineReady?`Offline ready (${offlineProfile}) · refresh core`:c.download}</button><button className="secondary wide" disabled={busy} onClick={()=>prepare('full')}><Download size={17}/>{sw?'Hifadhi AI yenye uwezo zaidi · MB 48':'Save richer AI offline · 48 MB'}</button></>}{progress&&<p role="status" className="setup-progress">{progress}</p>}<button className="secondary wide" disabled={busy} onClick={activateSemantic}><FlaskConical size={17}/>{semantic?'Refresh semantic analysis':'Use richer on-device analysis'}</button>{!desktop&&<><button className="secondary wide" onClick={()=>installPrompt?installPrompt.prompt():toast.info('On Android: browser menu → Install app. On iPhone: Share → Add to Home Screen. Install after offline preparation.')}><Plus size={17}/>{c.install}</button><p className="small-note">Initial setup needs a connection or the supplied offline package. A basic call-only phone cannot run this app. Use the household smartphone.</p></>}<p className="small-note">{desktop?'This desktop edition is for demonstration and operator use. The mobile web edition supports the challenge’s household smartphone workflow.':'Export a backup regularly. Browser storage can be cleared by your device.'}</p></section>
 <section className="panel"><div className="panel-heading"><h2>{c.privacy}</h2><LockKeyhole size={20}/></div><p className="device-copy">{sw?'Hakuna akaunti, hakuna kupakia maoni, hakuna matangazo. Maoni yanahifadhiwa kwenye kivinjari hiki. Mtu anayetumia simu iliyofunguliwa anaweza kuyasoma.':'No account, no feedback uploads, no advertising. Comments stay in this browser. Anyone with access to the unlocked phone can read them.'}</p><ul className="privacy-list"><li><Check size={15}/>Consent is required before saving feedback.</li><li><Check size={15}/>Email addresses and phone numbers are removed automatically.</li><li><Info size={15}/>Names and other identifiers still need manual removal.</li><li><Info size={15}/>Use the phone’s screen lock; this notebook is not encrypted.</li></ul><div className="backup-buttons"><button className="secondary" onClick={()=>download(`fieldnotes-${today()}.json`,JSON.stringify(state,null,2))}><Download size={17}/>{c.export}</button><button className="secondary" onClick={()=>fileInput.current?.click()}><Upload size={17}/>{c.import}</button></div><input ref={fileInput} type="file" accept="application/json,.json" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)restore(file);e.target.value='';}}/><button className="danger-link" onClick={()=>setDeleteOpen(true)}><Trash2 size={15}/>{c.deleteAll}</button><label className="field-label">{c.newBusiness}<input className="text-input" maxLength={70} value={state.business} onChange={e=>set({business:e.target.value})}/></label></section>
 <section className="panel provenance"><div className="panel-heading"><h2>{sw?'Lugha na mipaka':'Languages & limitations'}</h2><Globe size={20}/></div><p>English comments are analyzed. Kiswahili operator instructions and action cards work offline. Non-English feedback is preserved for human review. Optional message translation is available in visitor requests; it does not automatically classify translated reviews.</p><p>The Kiswahili copy is a draft and requires native-speaker validation before field deployment. Original English evidence remains visible; a bilingual guide may be needed.</p><p>Demo and training comments are authored synthetic examples. They are not a customer survey. Very short, sarcastic, mixed or unrelated feedback can be misclassified.</p><button className="text-button" onClick={()=>setShowEvaluation(true)}><FlaskConical size={16}/>{c.heldout}<ChevronRight size={14}/></button></section><section className="panel provenance"><div className="panel-heading"><h2>Data & model sources</h2><BookOpen size={20}/></div><p>World Bank Small AI challenge: Noor’s tourism workflow and device constraints. Ondera is fictional; no real farm is represented.</p><p>Compact model: 72 authored examples, MIT. Semantic model: all-MiniLM-L6-v2, Apache 2.0. No guest comments are used to train either model.</p><p>Theme suggestions are fixed, editable starting points. A similarity score is not a probability of correctness. Nothing is booked, posted, or sent automatically.</p></section></div>}
 </main></div>
 <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent className="noor-dialog"><DialogHeader><DialogTitle>{c.add}</DialogTitle><DialogDescription>{c.local} Remove names and identifying details.</DialogDescription></DialogHeader><label className="field-label">{c.text}<textarea value={newText} onChange={e=>setNewText(e.target.value)} maxLength={5000} rows={5} placeholder="The guest’s original words…"/></label><label className="checkbox-label"><Checkbox checked={batch} onCheckedChange={v=>setBatch(v===true)}/>{c.batch} <small>(separate with a blank line)</small></label><div className="form-grid"><label className="field-label">{c.date}<input className="text-input" type="date" value={newDate} onChange={e=>setNewDate(e.target.value)}/></label><div className="field-label">{c.rating}<Select value={newRating} onValueChange={setNewRating}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Not provided</SelectItem>{[1,2,3,4,5].map(n=><SelectItem key={n} value={String(n)}>{n} / 5</SelectItem>)}</SelectContent></Select></div><label className="field-label">{c.sourceLabel}<input className="text-input" value={newSource} onChange={e=>setNewSource(e.target.value)} maxLength={100}/></label><div className="field-label">Feedback language<Select value={newLanguage} onValueChange={setNewLanguage}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="en">English</SelectItem><SelectItem value="sw">Kiswahili · human review</SelectItem><SelectItem value="other">Other · human review</SelectItem></SelectContent></Select></div></div><label className="checkbox-label consent-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>{c.consent}</span></label><div className="dialog-actions"><button className="secondary" onClick={()=>setAddOpen(false)}>{c.cancel}</button><button className="primary" disabled={!consent||!newText.trim()||busy} onClick={addFeedback}>{busy?<Loader2 size={17} className="spin"/>:<Check size={17}/>} {c.save}</button></div></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="noor-dialog evidence-dialog"><DialogHeader><DialogTitle>{selected?(sw?selected.sw:selected.en):c.details}</DialogTitle><DialogDescription>{c.await} {c.actionHelp}</DialogDescription></DialogHeader>{selected&&<><div className="evidence-summary"><strong>{selected.mentions}</strong><span>{sw?'maoni yanataja mada hii':'distinct comments mention this theme'}</span><span className="tone-pill improve">{selected.issues} {sw?'mabadiliko':'requests for change'}</span></div><div className="evidence-scroll">{selected.evidence.map((e,i)=><div className="evidence-quote" key={i}><p>“{e.quote}”</p><span>{displayDate(e.review.date)} · {e.review.synthetic?c.synthetic:e.review.source} · {c[e.tone]}</span></div>)}</div><div className="suggestion-box"><Lightbulb size={20}/><div><span>{sw?'Pendekezo':'A suggestion to consider'}</span><strong>{sw?selected.actionSw:selected.actionEn}</strong></div></div><label className="field-label">{c.note}<textarea rows={2} value={planNote} onChange={e=>setPlanNote(e.target.value)} placeholder={sw?'Utafanya nini, na lini?':'What would you change, and when?'} maxLength={1000}/></label><div className="dialog-actions"><button className="secondary" onClick={()=>setDetail(null)}>{c.cancel}</button><button className="primary" disabled={!selected.mentions} onClick={()=>plan(selected.id)}><Check size={17}/>{c.plan}</button></div></>}</DialogContent></Dialog>
 <Dialog open={!!resultOpen} onOpenChange={open=>!open&&setResultOpen(null)}><DialogContent className="noor-dialog"><DialogHeader><DialogTitle>{c.complete}</DialogTitle><DialogDescription>Describe what you changed and what you observed. Avoid assuming that the change caused an outcome.</DialogDescription></DialogHeader><textarea aria-label="Observed outcome" rows={5} value={resultText} onChange={e=>setResultText(e.target.value)} maxLength={2000}/><button className="primary" disabled={!resultText.trim()} onClick={()=>{setState(s=>({...s,experiments:s.experiments.map(e=>e.id===resultOpen?.id?{...e,status:'complete',result:scrub(resultText)}:e)}));setResultOpen(null);}}>{sw?'Hifadhi matokeo':'Save observed outcome'}</button></DialogContent></Dialog>
 <Dialog open={showEvaluation} onOpenChange={setShowEvaluation}><DialogContent className="noor-dialog"><DialogHeader><DialogTitle>Evaluation & evidence</DialogTitle><DialogDescription>Small authored test suite. This is a prototype check, not field validation.</DialogDescription></DialogHeader>{evaluation?<><div className="evaluation-stats"><div><strong>{evaluation.total}</strong><span>test comments</span></div><div><strong>{Math.round(evaluation.semanticAccuracy*100)}%</strong><span>semantic exact accuracy</span></div><div><strong>{Math.round(evaluation.baselineAccuracy*100)}%</strong><span>keyword baseline</span></div></div><p>Cases include paraphrases, unknown topics, terse comments and unsupported languages. Uncertain cases must abstain. Tone uses explicit cues and is not a validated sentiment model.</p><p>Compact fallback exact accuracy: {Math.round(evaluation.compactAccuracy*100)}%. It favors abstention; accepted-case accuracy is measured separately. Test labels and results are provided in the source package. Real visitor data, device tests and native-language review remain necessary.</p><a className="text-button" href="/evaluation.json" download>Download complete evaluation</a></>:<p>Evaluation results will be available after the build checks finish.</p>}</DialogContent></Dialog>
 <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{c.deleteAll}</AlertDialogTitle><AlertDialogDescription>This removes feedback and plans from this browser. Exported backups remain wherever you saved them. Offline app files remain installed.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{c.cancel}</AlertDialogCancel><AlertDialogAction onClick={()=>{setState({...DEFAULT_STATE,reviews:[],experiments:[],mode:'own',language:state.language,business:state.business});toast.success('Feedback and plans deleted.');}}>{c.delete}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={ownOpen} onOpenChange={setOwnOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{c.own}</AlertDialogTitle><AlertDialogDescription>Start an empty notebook. This removes the example comments and existing plans from this device. Export anything you want to keep first.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{c.cancel}</AlertDialogCancel><AlertDialogAction onClick={()=>{setState({...DEFAULT_STATE,reviews:[],experiments:[],mode:'own',language:state.language,business:state.business});setAddOpen(true);}}>Start my notebook</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Toaster position="bottom-right" richColors/>
 </SidebarProvider>;
}
function ReviewCard({review:r,c,sw,onOpen}:{review:Review;c:(typeof COPY)[keyof typeof COPY];sw:boolean;onOpen:()=>void}){const first=r.analysis?.find(a=>a.theme);return <button className="panel preview-card" onClick={onOpen}><div className="preview-meta"><span className="guest-avatar"><MessageSquare size={16}/></span><span>{r.synthetic?c.synthetic:r.source}<small>{displayDate(r.date)}</small></span><span className="stars"><Star size={12} fill="currentColor"/>{r.rating??'—'}</span></div><p>“{r.text}”</p><div className="preview-footer"><span className={`tone-pill ${first?.tone??'uncertain'}`}>{first?(sw?THEMES.find(t=>t.id===first.theme)!.sw:THEMES.find(t=>t.id===first.theme)!.en):c.ask}</span><ChevronRight size={15}/></div></button>;}
function Empty({title,text,onAdd,label}:{title:string;text:string;onAdd:()=>void;label:string}){return <div className="panel empty-state"><NotebookPen size={38}/><h2>{title}</h2><p>{text}</p><button className="primary" onClick={onAdd}>{label}</button></div>;}
