export type Language = 'en'|'sw';
export type ThemeId = 'participation'|'learning'|'directions'|'comfort'|'pacing'|'value';
export type Tone = 'positive'|'improve'|'uncertain';
export type Evidence = {theme:ThemeId|null; tone:Tone; score:number; margin:number; quote:string; start:number; end:number; corrected?:boolean};
export type Review = {id:string; text:string; date:string; rating:number|null; source:string; synthetic:boolean; consent:boolean; language:'en'|'sw'|'other'; analysis?:Evidence[]; excluded?:boolean};
export type Experiment = {id:string; theme:ThemeId; title:string; status:'planned'|'active'|'complete'; createdAt:string; startedAt?:string; baselineCount:number; baselineIssues:number; note:string; result?:string};
export type State = {version:1; language:Language; business:string; reviews:Review[]; experiments:Experiment[]; modelReady:boolean; mode:'demo'|'own';};
export const THEMES:{id:ThemeId;en:string;sw:string;description:string;actionEn:string;actionSw:string;effort:string;color:string;examples:{positive:string[];improve:string[]}}[] = [
 {id:'participation',en:'Hands-on experiences',sw:'Shughuli za kushiriki',description:'Picking, roasting, grinding, tasting and making things yourself.',actionEn:'Try a 15-minute roast-and-grind activity',actionSw:'Jaribu shughuli ya dakika 15 ya kuchoma na kusaga kahawa',effort:'Low effort',color:'#1b7564',examples:{positive:['Roasting and grinding our own coffee beans was the best part.','We loved picking ripe coffee berries and doing something ourselves.','The hands-on coffee tasting and making our own cup was wonderful.','My children really enjoyed trying the equipment and joining the activity.'],improve:['I wish we could roast the beans ourselves instead of just watching.','Please let visitors take part in picking, grinding or brewing the coffee.','There was too much watching and not enough doing things with our hands.','We wanted to participate in the coffee activity but could only look.']}},
 {id:'learning',en:'Stories & explanations',sw:'Hadithi na maelezo',description:'Understanding coffee, local history, language and the guide’s explanation.',actionEn:'Add a simple picture guide to the coffee story',actionSw:'Ongeza mwongozo wa picha kueleza hadithi ya kahawa',effort:'Low effort',color:'#4361c4',examples:{positive:['The guide explained how coffee grows clearly and told fascinating local stories.','We learned so much about the farm history and the coffee process.','The explanations were easy to understand and the guide answered our questions.','Noor told us about her family and the history of the village beautifully.'],improve:['It was hard to understand the explanations and we needed a translation.','I wanted more information about coffee growing and local history.','The guide spoke too quickly and the explanation was confusing.','Pictures or a translated explanation would help us understand the story.']}},
 {id:'directions',en:'Finding the farm',sw:'Kufika shambani',description:'Directions, signs, arrival, transport and finding the entrance.',actionEn:'Share a landmark-based arrival card before visits',actionSw:'Shiriki maelekezo yenye alama za eneo kabla ya ziara',effort:'Low effort',color:'#b45e20',examples:{positive:['Clear directions made it easy to find the farm entrance.','The signs at the road junction helped us arrive without getting lost.','Transport was straightforward and the guide met us at the gate.','The location instructions and landmarks were very helpful.'],improve:['We got lost on the way and could not find the entrance.','There were no signs at the road junction and the map sent us the wrong way.','Better directions before the visit would help people find the farm.','Our driver could not locate the gate and we arrived late.']}},
 {id:'comfort',en:'Comfort & accessibility',sw:'Faraja na ufikivu',description:'Shade, seats, toilets, drinking water and accessibility.',actionEn:'Add a shaded rest stop with drinking water',actionSw:'Ongeza sehemu ya kupumzika yenye kivuli na maji ya kunywa',effort:'Medium effort',color:'#8a4caf',examples:{positive:['The shaded seats and clean toilets made the visit comfortable.','We appreciated the drinking water and somewhere to rest.','The path was accessible and my older mother could enjoy the visit.','There was a comfortable place to sit out of the hot sun.'],improve:['It was very hot and there was nowhere to sit in the shade.','We needed drinking water and a clean toilet during the tour.','The steep uneven path was difficult for my elderly father to walk.','Please add benches and a resting place for visitors.']}},
 {id:'pacing',en:'Timing & pace',sw:'Muda na mwendo',description:'Duration, waiting, start time and speed of the tour.',actionEn:'Offer a clearly timed tour with a short rest break',actionSw:'Toa ziara yenye muda wazi na mapumziko mafupi',effort:'Low effort',color:'#a33e55',examples:{positive:['The tour started on time and the pace felt relaxed.','A ninety-minute visit was just the right length for us.','We had enough time at each stop without rushing.','There was no waiting and everything followed the planned schedule.'],improve:['We waited too long for the tour to start.','The visit felt rushed and we wanted more time at each stop.','The tour lasted much longer than we expected and we missed our bus.','Please tell guests how long the visit takes and start at the agreed time.']}},
 {id:'value',en:'Price & expectations',sw:'Bei na matarajio',description:'Price clarity, inclusions, payment and value for money.',actionEn:'Show one clear price and what it includes',actionSw:'Onyesha bei moja wazi na huduma zinazojumuishwa',effort:'Low effort',color:'#897016',examples:{positive:['The price was clear and the visit was good value for money.','The tasting was included and payment was easy.','We knew exactly what was included in the ticket price.','The experience was worth what we paid and there were no hidden fees.'],improve:['We did not know the price until we arrived and the tasting cost extra.','The extra charges were a surprise and payment was confusing.','Please explain what is included in the ticket before people book.','The cost was higher than expected and we did not feel it was good value.']}}
];
export const INITIAL_REVIEWS:Review[] = [
 ['Roasting a handful of beans ourselves was the highlight. I would happily come back for a longer workshop.',5,'2026-09-29'],
 ['We loved the farm, but we got lost after the bridge. A photo of the turning would have saved us half an hour.',3,'2026-09-28'],
 ['Noor explained the journey from berry to cup so clearly. Her family story made the visit feel personal.',5,'2026-09-28'],
 ['I wish we had been allowed to use the grinder instead of only watching the demonstration.',4,'2026-09-27'],
 ['There was nowhere to rest out of the sun. My mother needed a seat and some water.',3,'2026-09-26'],
 ['Our children loved picking the ripe berries. Making their own cup at the end was a lovely touch.',5,'2026-09-25'],
 ['The ticket price was clear and included the tasting. Very good value for an afternoon.',5,'2026-09-24'],
 ['It was difficult to find the gate. The directions mentioned a shop that had closed.',3,'2026-09-23'],
 ['The guide spoke so fast that I could not follow the explanation. Pictures would have helped.',3,'2026-09-22'],
 ['Watching the beans being roasted was interesting. Next time I would love to try it myself.',4,'2026-09-21'],
 ['The tour started forty minutes late and we had to leave before the tasting.',2,'2026-09-20'],
 ['The village history and the explanation about the coffee harvest were fascinating.',5,'2026-09-19'],
 ['A hands-on roasting class would be worth a second trip. We wanted to get involved rather than just look.',4,'2026-09-18'],
 ['The shaded bench at the tasting area was welcome after the walk. Clean drinking water was available.',5,'2026-09-17'],
 ['We enjoyed the experience but a sign at the fork in the road would make arrival easier.',4,'2026-09-16'],
 ['The visit took nearly three hours although we had been told one hour. We missed our transport.',2,'2026-09-15'],
 ['Picking and sorting the berries ourselves helped us appreciate the work behind a cup of coffee.',5,'2026-09-14'],
 ['I was surprised to pay extra for the tasting. Please show all the costs before booking.',2,'2026-09-13'],
 ['The walk was a little steep for my father. A place to sit halfway would make it more accessible.',3,'2026-09-12'],
 ['A perfect slow morning. The guide left enough time for questions and never rushed us.',5,'2026-09-11'],
 ['The taxi driver struggled to find the entrance. Please send landmark directions in advance.',3,'2026-09-10'],
 ['Coffee is now my favourite subject. Noor answered every question about how the farm works.',5,'2026-09-09'],
 ['Could we have a little more practical time grinding and brewing? That would make a great workshop.',4,'2026-09-08'],
 ['Great.',4,'2026-09-07']
].map(([text,rating,date],i)=>({id:`demo-${i+1}`,text:String(text),rating:Number(rating),date:String(date),source:'Scenario demonstration',synthetic:true,consent:true,language:'en'}));
export const DEFAULT_STATE:State={version:1,language:'en',business:'Ondera Coffee Farm',reviews:INITIAL_REVIEWS,experiments:[],modelReady:false,mode:'demo'};
export function scrub(text:string){return text.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[email removed]').replace(/(?:\+?\d[\d\s().-]{7,}\d)/g,'[phone removed]').trim().slice(0,5000);}
export function splitQuotes(text:string){const parts:{quote:string;start:number;end:number}[]=[];const re=/[^.!?\n]+[.!?]?/g;let match;while((match=re.exec(text))){const raw=match[0];const trim=raw.trim();if(trim){const offset=raw.indexOf(trim);parts.push({quote:trim,start:match.index+offset,end:match.index+offset+trim.length});}}return parts.length?parts:[{quote:text,start:0,end:text.length}];}
export function uniqueReviews(reviews:Review[]){const seen=new Set<string>();return reviews.filter(r=>{const key=r.text.toLowerCase().replace(/\W/g,'');if(r.excluded||seen.has(key))return false;seen.add(key);return true;});}
export function summarize(reviews:Review[]){const valid=uniqueReviews(reviews);return THEMES.map(theme=>{const evidence=valid.flatMap(r=>(r.analysis??[]).filter(a=>a.theme===theme.id).map(a=>({...a,review:r})));const mentions=new Set(evidence.map(e=>e.review.id)).size;const issues=new Set(evidence.filter(e=>e.tone==='improve').map(e=>e.review.id)).size;const praise=new Set(evidence.filter(e=>e.tone==='positive').map(e=>e.review.id)).size;return {...theme,evidence,mentions,issues,praise,priority:issues*2+mentions};}).sort((a,b)=>b.priority-a.priority);}
// A model pass cannot overrule a human decision or resurrect deleted data.
export function mergeAnalysis(current:Review[],analyzed:Review[]):Review[]{
 const results=new Map(analyzed.map(r=>[r.id,r]));
 return current.map(r=>{const next=results.get(r.id);if(!next||next.text!==r.text)return r;
  return {...r,analysis:next.analysis?.map(a=>{const human=r.analysis?.find(h=>h.corrected&&h.start===a.start&&h.end===a.end&&h.quote===a.quote);return human?{...a,theme:human.theme,tone:human.tone,corrected:true}:a;})};
 });
}
export function validateImport(value:unknown):State{
 if(!value||typeof value!=='object')throw new Error('This is not a Fieldnotes backup.');
 const v=value as State;if(v.version!==1||!Array.isArray(v.reviews)||v.reviews.length>1000)throw new Error('Unsupported backup or too many comments.');
 const ids=new Set<string>();const reviews=v.reviews.map(r=>{
  if(!r||typeof r.text!=='string'||typeof r.id!=='string'||r.text.length>5000||r.consent!==true||ids.has(r.id))throw new Error('Invalid, duplicate or non-consented feedback.');ids.add(r.id);
  const text=scrub(r.text);const analysis=Array.isArray(r.analysis)?r.analysis.filter(a=>a&&a.corrected===true&&Number.isInteger(a.start)&&Number.isInteger(a.end)&&a.start>=0&&a.end<=text.length&&a.end>a.start&&text.slice(a.start,a.end)===a.quote&&(a.theme===null||THEMES.some(t=>t.id===a.theme))&&['positive','improve','uncertain'].includes(a.tone)).map(a=>({...a,score:0,margin:0})):undefined;
  return {id:r.id,text,date:typeof r.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)?r.date:new Date().toISOString().slice(0,10),rating:Number.isInteger(r.rating)&&r.rating!>=1&&r.rating!<=5?r.rating:null,source:typeof r.source==='string'?scrub(r.source).slice(0,100):'Restored feedback',synthetic:r.synthetic===true,consent:true,language:['en','sw','other'].includes(r.language)?r.language:'other',analysis,excluded:r.excluded===true} as Review;
 });
 const experiments=Array.isArray(v.experiments)?v.experiments.filter(e=>e&&typeof e.id==='string'&&THEMES.some(t=>t.id===e.theme)&&['planned','active','complete'].includes(e.status)).slice(0,100).map(e=>({...e,title:typeof e.title==='string'?e.title.slice(0,300):'',note:typeof e.note==='string'?scrub(e.note):'',result:typeof e.result==='string'?scrub(e.result):undefined,createdAt:typeof e.createdAt==='string'?e.createdAt:new Date().toISOString(),baselineCount:Number.isFinite(e.baselineCount)?Math.max(0,e.baselineCount):0,baselineIssues:Number.isFinite(e.baselineIssues)?Math.max(0,e.baselineIssues):0})):[];
 return {...DEFAULT_STATE,language:v.language==='sw'?'sw':'en',business:typeof v.business==='string'?scrub(v.business).slice(0,100):DEFAULT_STATE.business,mode:v.mode==='demo'?'demo':'own',reviews,experiments,modelReady:false};
}
